config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'blogs#index'
  get 'comments/create'

  resources :blogs do
    resources :comments
  end
  mount LetterOpenerWeb::Engine, at: "/inbox" if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  has_many :comments, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :blog
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :avatar


  def avatar_thumbnail
    if avatar.attached?
      avatar.variant(resize: "150x150!").processed
    else
      "/default-avatar.jpg"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?
    protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:avatar])
      devise_parameter_sanitizer.permit(:account_update, keys: [:avatar])
    end

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    @comments = @blog.comments
    @comment = @blog.comments.build
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.js { render :index }
        #format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.js { render :index }
        #format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_params
      params.require(:blog).permit(:title, :content)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_blog, only: [:create, :edit, :update]
  # Une action pour enregistrer et publier un commentaire.
 def create
   # Recherchez Blog à partir de la valeur du paramètre et créez-le en tant que commentaires associés à Blog.
   @blog = Blog.find(params[:blog_id])
   @comment = @blog.comments.build(comment_params)
   # Changer le format en fonction de la demande du client
   respond_to do |format|
     if @comment.save
       format.js { render :index }
       #format.html { redirect_to blog_path(@blog) }
     else
       format.html { redirect_to blog_path(@blog), notice: 'Impossible de publier ...' }
     end
   end
 end
 def edit
    @comment = @blog.comments.find(params[:id])
    respond_to do |format|
      flash.now[:notice] = 'commentaire modifié'
      format.js { render :edit }
    end
  end
  def update
    @comment = @blog.comments.find(params[:id])
      respond_to do |format|
        if @comment.update(comment_params)
          flash.now[:notice] = 'Le commentaire a été modifié'
          format.js { render :index }
        else
          flash.now[:notice] = 'Le modificateur de commentaire a échoué'
          format.js { render :edit_error }
        end
      end
    end
    def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    respond_to do |format|
      flash.now[:notice] = 'Commentaire supprimé'
      format.js { render :index }
    end
  end
 private
 # Paramètres forts
 def comment_params
   params.require(:comment).permit(:blog_id, :content)
 end
 def set_blog
    @blog = Blog.find(params[:blog_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blogs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.title %></td>
        <td><%= blog.content %></td>
        <td><%= link_to 'Show', blog %></td>
        <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
        <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  <div class="blog-text">
    <p><strong>Titre</strong>：<%= @blog.title %></p>
    <p><strong>Le contenu</strong>：<%= @blog.content %></p>
  </div>
  <p>Liste des commentaires (Le contenu ci-dessous est important)</p>
  <!-- Obtenez l'ID HTML de cette zone de commentaires et ne mettez à jour que cette div -->
  <div id="comments_area">
    <!-- Rendu pour afficher une liste des commentaires publiés sur la page des détails du blog -->
    <%= render partial: 'comments/index', locals: { comments: @comments, blog: @blog } %>
  </div>
  <!-- rendre pour afficher la boîte de commentaires sur la page de détail du blog -->
  <%= render partial: 'comments/form', locals: { comment: @comment, blog: @blog } %>
  <%= link_to 'Modifier', edit_blog_path(@blog) %> |
  <%= link_to 'Retour', blogs_path %>
</div>

app/views/comments/_edit.html.erb
<%= form_with(model: [blog, comment]) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>
      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.text_area :content, id: "comment_content_#{blog.id}" %>
    <%= form.label :content %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/_form.html.erb
<!-- Ce sera la boîte de commentaires qui apparaîtra sur l'écran d'affichage du blog -->
<%= form_with(model: [blog, comment]) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>
      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/_index.html.erb
<ul>
  <% comments.each do |comment| %>
    <% if comment.id.present? %>
      <li>
        <div class="comment-content" id ="this_comment_<%= comment.id %>"></div>
        <p><%= comment.content %></p>
        <p>
        <span><%= link_to "modifier", edit_blog_comment_path(blog, comment), remote: true %></span>
        <span><%= link_to "supprimer", blog_comment_path(comment.blog_id, comment.id), method: :delete, remote: true,
                                        data: { confirm: "Voulez-vous vraiment supprimer ?"} %></span>
        </p>
      </li>
    <% end %>
  <% end %>
</ul>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/edit.js.erb
$("#this_comment_<%= @comment.id %>").replaceWith("<%= j render 'comments/edit', blog: @blog, comment: @comment %>");

app/views/comments/index.js.erb
$("#comments_area").html("<%= j(render 'comments/index', { comments: @comment.blog.comments, blog: @comment.blog }) %>")
$("textarea").val('')

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ajax</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div>
    <% flash.each do |key, value|%>
      <%= content_tag(:div,value,class:"alert alert-#{key}")%>
    <% end%>
  </div>
  <div class="">
    <% if user_signed_in? %>
      <button type="button" name="button"><%= link_to "logout", destroy_user_session_path, method: :delete %></button>
      <button type="button" name="button"><%= link_to "user params", edit_user_registration_path %></button>
      <br>
     <%= image_tag (current_user.avatar_thumbnail) %>
    <% else %>

      <%= link_to "sign up", new_user_registration_path %>
      <%= link_to "login", new_user_session_path %>
   <% end %>
    <%= yield %>
  </body>
</html>